title: "Jonathan Bastard personal page"
description: "Epidemiology and modelling of infectious diseases."
author: Jonathan Bastard
email: jonathan . bastard @ anses . fr
theme: minima
header_pages:
  - index.md
  - CV.md
  - research.md
